### ISSUE TITLE
質問箱一覧ページが欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/tallk#3]

**Comment by KishiKyousuke** [comment]
@komagata 
[fjordllc/tallk: 平等にトークテーマを提案できるアプリ。](https://github.com/fjordllc/tallk)のリポジトリにpushを行いたいのですが`permission denied`のエラーが起きてしまいます💦
何か認証が必要となるのでしょうか❓

**Comment by komagata** [comment]
@KishiKyousuke すみません、権限設定ができていなかったのでただいま設定しました。もう一度試していただければ〜
